version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: medevice_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Thulasi@2001
      MYSQL_DATABASE: medevice_db
      MYSQL_USER: medevice_user
      MYSQL_PASSWORD: medevice_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: medevice_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Thulasi@2001
    ports:
      - "8080:80"

  metabase:
    image: metabase/metabase:latest
    container_name: medevice_metabase
    restart: always
    ports:
      - "3001:3000"
    environment:
      MB_DB_FILE: /metabase.db/metabase.db
    volumes:
      - ./metabase_data:/metabase.db
